"use client";

import React, { useMemo } from "react";
import Link from "next/link";
import PageBreadCrumb from "@/components/common/PageBreadCrumb";
import { useAuth } from "@/context/AuthContext";
import { ANALYTICS_SECTIONS } from "@/lib/analytics/sections";

export default function AnalyticsHubPage() {
  const { hasPermission } = useAuth();

  const visibleSections = useMemo(
    () => ANALYTICS_SECTIONS.filter((section) => hasPermission(section.permission)),
    [hasPermission]
  );

  return (
    <div>
      <PageBreadCrumb pageTitle="Analytics" />
      <p className="mt-2 max-w-3xl text-sm text-gray-600 dark:text-gray-400">
        Each section below is a full report for a chosen branch and date range: headline figures, charts, detailed
        tables, and a written analysis generated by ChatGPT.
      </p>

      {visibleSections.length === 0 ? (
        <p className="mt-8 text-sm text-gray-500 dark:text-gray-400">
          You do not have permission to view any analytics section.
        </p>
      ) : (
        <div className="mt-8 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
          {visibleSections.map((section) => (
            <Link
              key={section.key}
              href={section.path}
              className="group flex h-full flex-col rounded-2xl border border-gray-200 bg-white p-5 transition hover:border-brand-300 hover:shadow-sm dark:border-gray-800 dark:bg-white/3 dark:hover:border-brand-500/40"
            >
              <h2 className="text-base font-semibold text-gray-900 group-hover:text-brand-600 dark:text-white dark:group-hover:text-brand-400">
                {section.name}
              </h2>
              <p className="mt-2 flex-1 text-sm text-gray-600 dark:text-gray-400">{section.description}</p>
              <span className="mt-4 text-sm font-medium text-brand-600 dark:text-brand-400">Open report →</span>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
